# Generated by Django 3.0.3 on 2020-02-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='card_images')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
